// 'use client'
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { AiTwotoneHome } from "react-icons/ai";
import { FaRegHeart } from "react-icons/fa";
import { LuUser } from "react-icons/lu";
import Link from "next/link";
// import { useState } from "react";


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Real-State",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  // const [change, setChange] =useState(false);
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
      <nav className="flex justify-around w-full text-black items-center h-16 bg-white shadow-sm">
      <div  className="flex space-x-2 w-50 text-blue-500  ">
<AiTwotoneHome className="text-3xl" />
<h1 className="text-xl font-bold hover:border-b border-blue-500">RealEstate</h1>
 </div>
<ul className="flex space-x-4 px-2">
<Link className=" hover:border-b border-gray-500" href="/components/buy">Buy</Link>  
<Link className=" hover:border-b border-gray-500" href="/components/rent">Rent</Link>  
<Link className=" hover:border-b border-gray-500" href="/components/sell">Sell</Link>  
<Link className=" hover:border-b border-gray-500" href="/components/about">About</Link>  
</ul>
<div className="flex space-x-4 p-1 w-100 justify-end">
<FaRegHeart className="text-2xl flex items-center"/>
<div className="flex space-x-2 items-center bg-blue-500 text-white p-2 rounded-lg transition-transform duration-300 hover:scale-105 cursor-pointer">
<LuUser size={30}/>
<Link href="#">Sign In</Link>
</div>
</div>
     
      </nav>
        {children}
      </body>
    </html>
  );
}
